[main]
  serialize = "{version}-{banner}"
  tag = true
  version = "1.1.0"

[[operate]]
  location = "cmd/onefinger/main.go"
  replace = "__version__ = \"{}\""
  search = "__version__ = \"{}\""

[[operate]]
  location = "cmd/onefinger/main.go"
  replace = "onefinger {}"
  search = "onefinger {}"