[main]
  version   = "1.0.0"
  tag       = true
  serialize = "{version}-{banner}"
[[operate]]
  location = "cmd/onefinger/main.go"
  search   = "__version__ = \"{}\""
  replace  = "__version__ = \"{}\""
